### ISSUE TITLE
undefined: newWindow

### ISSUE THREAD

**Issue by heary29** [Inkeliz/gowebview#21]
Hi, when I use the example in Getting Started to compile under linux, I get an error message with the go build command: "/home/heary/GOPATH/pkg/mod/github.com/inkeliz/gowebview@v1.0.1 /gowebview.go:88:9: undefined: newWindow ” Because I used the same code before, it has run successfully on windows, but I will have this error when moving to Linux, is there something wrong with my settings, please help me one time

**Comment by inkeliz** [comment]
Currently, gowebview don't support Linux, macOS and iOS. If you want support for Linux and macOS you should use https://github.com/webview/webview instead. 

I have no plans to implement Linux support. Support for macOS and iOS will be added at some point.

**Comment by heary29** [comment]
ok, thank you very much for the detailed answer, it helped me a lot
